language: python

sudo: required

dist: xenial

python:
  - "3.6"
  - "3.7"

cache:
  pip: true
  directories:
    - .hypothesis
    - .eggs

install:
  - sudo apt-add-repository -y ppa:nextgis/dev
  - sudo apt update
  - sudo apt install -y libgdal-dev libnetcdf-dev

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: python setup.py test

after_success:
  if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then
    ./cc-test-reporter format-coverage -t coverage.py test-reports/coverage.xml;
    ./cc-test-reporter upload-coverage;
    pip install codacy-coverage;
    python-codacy-coverage -r test-reports/coverage.xml;
  fi

deploy:
  provider: pypi
  user: "nlesc"
  skip_existing: true
  on:
    tags: true
    python: '3.7'
  password:
    secure: "HQnUOySc1Dn5JM7k4H5sGMOBxsh7mMJANbEUgbymQrDICXT2bL12EvCl/YKTOB2laqpL+8lnk8eSn6xKZRLbNB/vxvpiuAVqe2e6FAwTnwReQEJ3y691jYxxYBHAmttwB1qSMmrmkXLd9BMgaEj7Z75wj53L7wvOkbXTBpBZqpKXS3yWx6EJFp25ZCBzVgob6v9qAhnjIFdNxzyoeG4CFHIgCjtU2/RemS/75fBmqvsEWK/HL0/f//sNhorL2s/rzeCWJKIe+VsGJqA92n0/ODS8XafDCrL8KzQ1mPPx2756QaiBz6yXXZwo1/aF2FzrGQAtJAhyHYMi7ffRn3HOdqKHCv0+644H4TsxqnYPohfeoOxrmTbamnsyFkFwZW6RSl1Gmfl4uE4Rm6fxVjLXNtW6yj+g08KrH50OXIJArW5iXM8RTpvjsFC7lRKh6jdoNjYqFtgy/8fNPIlbEdPU8SMxma++xG51LZo07iEFUxmuakFN0NVoKkxlto6i5VmS1+VHfvtkeHi6D3a6Bliz+6QMZ2L+Hc6g27oIboro8kAxiEIf1KTZaksP5YTtdUo3T5xUMOdNw5W3s5Uqi3uDpsEnaDDndIb9Ud8KvI37OHHT09kqCwXLIKC5PjwCvGpsDvwyojYd+QaOiOzBr+D4SYVqi+FznnZWgO+dz4voMro="
